# -*- coding: utf-8 -*-
"""TUGAS BESAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPo0J6gIrB5GBDD3n4DrNvTw4Fdq_fl3
"""

# ===============================================
#   QUIZ SEDERHANA
# ===============================================

import json
import os
import random
from datetime import datetime

SOAL_FILE = "soal.json"
SKOR_FILE = "skor.json"

# ---------------------------
# DEFAULT SOAL
# ---------------------------
DEFAULT_SOAL = [
    {
        "pertanyaan": "1. Ibu kota Indonesia adalah?",
        "pilihan": ["Jakarta", "Bandung", "Surabaya", "Medan", "Depok"],
        "jawaban_index": 0
    },
    {
        "pertanyaan": "2. Benua terbesar di dunia adalah?",
        "pilihan": ["Afrika", "Antartika", "Asia", "Eropa", "Australia"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "3. Planet yang dijuluki sebagai Planet Merah adalah?",
        "pilihan": ["Bumi", "Mars", "Jupiter", "Venus", "Saturnus"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "4. Lambang kimia dari air adalah?",
        "pilihan": ["CO2", "H2O", "O2", "N2", "H2"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "5. Hewan tercepat di darat adalah?",
        "pilihan": ["Singa", "Serigala", "Cheetah", "Harimau", "Zebra"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "6. Mata uang Jepang adalah?",
        "pilihan": ["Won", "Yuan", "Dollar", "Euro", "Yen"],
        "jawaban_index": 4
    },
    {
        "pertanyaan": "7. Gunung tertinggi di dunia adalah?",
        "pilihan": ["Kilimanjaro", "Fuji", "Elbrus", "Everest", "Aconcagua"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "8. Negara dengan penduduk terbanyak adalah?",
        "pilihan": ["India", "Amerika", "Rusia", "Cina", "Indonesia"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "9. Siapakah penemu lampu?",
        "pilihan": ["Albert Einstein", "Isaac Newton", "Galileo", "Nikola Tesla", "Thomas Edison"],
        "jawaban_index": 4
    },
    {
        "pertanyaan": "10. Contoh energi terbarukan adalah?",
        "pilihan": ["Batu bara", "Minyak bumi", "Angin", "Gas alam", "Uranium"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "11. Hewan pemakan tumbuhan disebut?",
        "pilihan": ["Omnivora", "Karnivora", "Herbivora", "Insektivora", "Detritivora"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "12. Bentuk bumi adalah?",
        "pilihan": ["Segitiga", "Kotak", "Oval", "Bulat", "Kubus"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "13. Manusia bernapas menggunakan?",
        "pilihan": ["Kulit", "Insang", "Paru-paru", "Trakea", "Rongga hidung"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "14. Satelit alami bumi adalah?",
        "pilihan": ["Mars", "Bulan", "Matahari", "Venus", "Jupiter"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "15. Warna primer berikut adalah?",
        "pilihan": ["Merah", "Coklat", "Hitam", "Abu-abu", "Pink"],
        "jawaban_index": 0
    },
    {
        "pertanyaan": "16. Organ yang memompa darah adalah?",
        "pilihan": ["Lambung", "Ginjal", "Paru-paru", "Jantung", "Usus"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "17. Kerajaan Hindu-Buddha terbesar di Indonesia adalah?",
        "pilihan": ["Sriwijaya", "Majapahit", "Tarumanegara", "Kutai", "Singasari"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "18. Ibukota provinsi Jawa Timur adalah?",
        "pilihan": ["Bandung", "Medan", "Surabaya", "Semarang", "Denpasar"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "19. 10 × 10 = ?",
        "pilihan": ["50", "100", "150", "200", "250"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "20. Alat untuk mengukur suhu adalah?",
        "pilihan": ["Speedometer", "Altimeter", "Voltmeter", "Termometer", "Barometer"],
        "jawaban_index": 3
    }
]


DEFAULT_SKOR = []


# ---------------------------
# Utility load/save JSON
# ---------------------------
def load_json(path, default):
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as f:
            json.dump(default, f, indent=2, ensure_ascii=False)
        return default
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except:
        return default


def save_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


# Load file
soal_data = load_json(SOAL_FILE, DEFAULT_SOAL)
skor_data = load_json(SKOR_FILE, DEFAULT_SKOR)


# ======================================================
#   TRY STREAMLIT MODE
# ======================================================
def coba_jalankan_streamlit():
    try:
        import streamlit as st
        import matplotlib.pyplot as plt

        st.title("📘 Aplikasi Quiz Sederhana")

        menu = st.sidebar.selectbox(
            "Menu",
            ["Mulai Quiz", "Tambah Soal", "Riwayat Nilai", "Grafik Nilai"]
        )

        # ---------------------- MULAI QUIZ -----------------------
        if menu == "Mulai Quiz":
            st.header("📝 Mulai Quiz")

            if "quiz_state" not in st.session_state:
                random.shuffle(soal_data)
                st.session_state.quiz_state = {
                    "index": 0,
                    "benar": 0,
                    "soal": soal_data.copy()
                }

            qs = st.session_state.quiz_state
            total = len(qs["soal"])
            idx = qs["index"]
            data = qs["soal"][idx]

            st.write(f"Soal **{idx+1}/{total}**")
            st.subheader(data["pertanyaan"])

            pilihan = data["pilihan"]
            jawab = st.radio("Jawaban:", pilihan)

            if st.button("Kirim"):
                j = pilihan.index(jawab)
                if j == data["jawaban_index"]:
                    st.success("Benar! 🎉")
                    qs["benar"] += 1
                else:
                    st.error(f"Salah. Jawaban benar: **{pilihan[data['jawaban_index']]}**")

                qs["index"] += 1

                if qs["index"] >= total:
                    skor = round(100 * qs["benar"] / total, 2)
                    st.subheader("🎉 Quiz Selesai")
                    st.write(f"Benar: {qs['benar']} / {total}")
                    st.write(f"Nilai: {skor}")

                    skor_data.append({
                        "timestamp": datetime.now().isoformat(timespec='seconds'),
                        "skor": skor,
                        "benar": qs["benar"],
                        "total": total
                    })
                    save_json(SKOR_FILE, skor_data)

                    if st.button("Mulai Lagi"):
                        del st.session_state.quiz_state
                else:
                    st.rerun()

        # ---------------------- TAMBAH SOAL -----------------------
        if menu == "Tambah Soal":
            st.header("➕ Tambah Soal")

            pert = st.text_input("Pertanyaan:")
            p = []
            for i in range(1, 6):
                x = st.text_input(f"Pilihan {i}:")
                if x:
                    p.append(x)

            if len(p) >= 2:
                benar = st.selectbox("Jawaban benar:", list(range(1, len(p)+1)))
            else:
                benar = None

            if st.button("Simpan"):
                if not pert:
                    st.error("Pertanyaan kosong.")
                else:
                    soal_data.append({
                        "pertanyaan": pert,
                        "pilihan": p,
                        "jawaban_index": benar - 1
                    })
                    save_json(SOAL_FILE, soal_data)
                    st.success("Soal disimpan!")

        # ---------------------- RIWAYAT NILAI -----------------------
        if menu == "Riwayat Nilai":
            st.header("📄 Riwayat Nilai")
            if not skor_data:
                st.info("Belum ada data.")
            else:
                for i, e in enumerate(skor_data, start=1):
                    st.write(f"{i}. {e['timestamp']} — nilai {e['skor']} ({e['benar']}/{e['total']})")

        # ---------------------- GRAFIK NILAI -----------------------
        if menu == "Grafik Nilai":
            st.header("📊 Grafik Nilai")

            if not skor_data:
                st.info("Belum ada nilai.")
            else:
                ts = [e["timestamp"] for e in skor_data]
                val = [e["skor"] for e in skor_data]

                fig, ax = plt.subplots(figsize=(8,4))
                ax.plot(ts, val, marker="o")
                ax.set_title("Perkembangan Nilai")
                plt.xticks(rotation=45)

                st.pyplot(fig)

    except:
        return False  # Streamlit tidak tersedia
    return True



# ======================================================
#   MODE TERMINAL (COLAB / PYTHON)
# ======================================================
def mode_terminal():
    while True:
        print("\n=== APLIKASI QUIZ SEDERHANA ===")
        print("1. Mulai Quiz")
        print("2. Tambah Soal")
        print("3. Riwayat Nilai")
        print("4. Keluar")

        p = input("Pilih: ")

        if p == "1":
            soal = soal_data.copy()
            random.shuffle(soal)
            benar = 0

            for s in soal:
                print("\n" + s["pertanyaan"])
                for i, op in enumerate(s["pilihan"], start=1):
                    print(f"{i}. {op}")

                j = int(input("Jawab: ")) - 1
                if j == s["jawaban_index"]:
                    print("Benar!")
                    benar += 1
                else:
                    print("Salah.")

            skor = round(100 * benar / len(soal), 2)
            print(f"\nHasil: {benar}/{len(soal)} → Nilai {skor}")

            skor_data.append({
                "timestamp": datetime.now().isoformat(timespec='seconds'),
                "skor": skor,
                "benar": benar,
                "total": len(soal)
            })
            save_json(SKOR_FILE, skor_data)

        elif p == "2":
            print("\n=== Tambah Soal ===")
            pert = input("Pertanyaan: ")
            opsi = []
            while True:
                x = input(f"Pilihan {len(opsi)+1} (kosong = selesai): ")
                if x == "":
                    break
                opsi.append(x)

            print("Pilih jawaban benar:")
            for i, o in enumerate(opsi, start=1):
                print(f"{i}. {o}")
            jb = int(input("Jawaban benar: ")) - 1

            soal_data.append({
                "pertanyaan": pert,
                "pilihan": opsi,
                "jawaban_index": jb
            })
            save_json(SOAL_FILE, soal_data)

        elif p == "3":
            print("\n=== Riwayat Nilai ===")
            for e in skor_data:
                print(e)

        elif p == "4":
            print("Keluar...")
            break



# ======================================================
#   MAIN
# ======================================================
if not coba_jalankan_streamlit():
    print("Streamlit tidak terdeteksi → Mode Terminal (Colab) aktif.")
    mode_terminal()